"use strict";

const HTML = [
  '<!DOCTYPE html>',
  '<html lang="en">',
  '<head>',
  '<meta charset="UTF-8">',
  '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
  '<title>OpenProxyRouter Dashboard</title>',
  '<style>',
  '  :root{',
  '    --bg:#f5f7fb;--surface:#ffffff;--surface-2:#f9fafc;--surface-3:#eef2f7;',
  '    --border:#e5e7eb;--text:#0f172a;--muted:#64748b;--dim:#94a3b8;',
  '    --blue:#3b82f6;--green:#10b981;--amber:#f59e0b;--pink:#ec4899;--purple:#8b5cf6;',
  '    --cyan:#06b6d4;--orange:#f97316;--red:#ef4444;--indigo:#6366f1;',
  '    --shadow-sm:0 1px 2px rgba(15,23,42,0.04), 0 1px 3px rgba(15,23,42,0.06);',
  '    --shadow-md:0 2px 4px rgba(15,23,42,0.04), 0 4px 10px rgba(15,23,42,0.08);',
  '  }',
  '  *{box-sizing:border-box;margin:0;padding:0}',
  '  html,body{background:var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;font-size:14px;line-height:1.5;-webkit-font-smoothing:antialiased}',
  '  .wrap{max-width:1400px;margin:0 auto;padding:28px 24px}',
  '  .header{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:14px;margin-bottom:24px}',
  '  .header h1{font-size:22px;font-weight:700;color:var(--text);letter-spacing:-0.02em}',
  '  .header h1 .dot{display:inline-block;width:12px;height:12px;border-radius:50%;background:linear-gradient(135deg,var(--blue),var(--indigo));margin-right:10px;vertical-align:middle;box-shadow:0 0 0 4px rgba(59,130,246,0.14)}',
  '  .controls{display:flex;gap:4px;flex-wrap:wrap;align-items:center;background:var(--surface);padding:4px;border-radius:10px;box-shadow:var(--shadow-sm)}',
  '  .controls button{background:transparent;color:var(--muted);border:0;padding:7px 14px;border-radius:7px;cursor:pointer;font-size:12px;font-weight:600;transition:all 150ms;letter-spacing:0.02em}',
  '  .controls button:hover{background:var(--surface-3);color:var(--text)}',
  '  .controls button.active{background:linear-gradient(135deg,var(--blue),var(--indigo));color:#fff;box-shadow:0 2px 8px rgba(59,130,246,0.36)}',
  '  .controls #refreshBtn{background:var(--surface-3);color:var(--text);margin-left:4px}',
  '  .controls #refreshBtn:hover{background:var(--border)}',
  '  .banner{padding:12px 16px;border-radius:10px;font-size:13px;margin-bottom:18px;display:none;font-weight:500}',
  '  .banner.show{display:block}',
  '  .banner.warn{background:#fffbeb;border:1px solid #fde68a;color:#92400e}',
  '  .banner.err{background:#fef2f2;border:1px solid #fecaca;color:#991b1b}',
  '  .cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:14px;margin-bottom:28px}',
  '  .card{background:var(--surface);border-radius:14px;padding:18px 20px;box-shadow:var(--shadow-sm);position:relative;overflow:hidden;transition:transform 180ms ease,box-shadow 180ms ease}',
  '  .card:hover{transform:translateY(-2px);box-shadow:var(--shadow-md)}',
  '  .card::before{content:"";position:absolute;top:0;left:0;right:0;height:4px;background:var(--blue)}',
  '  .card.tone-blue::before{background:var(--blue)}',
  '  .card.tone-green::before{background:var(--green)}',
  '  .card.tone-amber::before{background:var(--amber)}',
  '  .card.tone-pink::before{background:var(--pink)}',
  '  .card.tone-purple::before{background:var(--purple)}',
  '  .card .label{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:0.06em;font-weight:700;margin-bottom:10px}',
  '  .card .value{font-size:30px;font-weight:800;font-variant-numeric:tabular-nums;line-height:1.1;letter-spacing:-0.02em;color:var(--text)}',
  '  .card.tone-blue .value{color:var(--blue)}',
  '  .card.tone-green .value{color:var(--green)}',
  '  .card.tone-amber .value{color:var(--amber)}',
  '  .card.tone-pink .value{color:var(--pink)}',
  '  .card.tone-purple .value{color:var(--purple)}',
  '  .card .sub{font-size:11px;color:var(--dim);margin-top:6px;font-weight:500}',
  '  .section{margin-bottom:24px}',
  '  .section-title{font-size:12px;font-weight:700;color:var(--muted);margin-bottom:12px;display:flex;justify-content:space-between;align-items:center;letter-spacing:0.06em;text-transform:uppercase}',
  '  .section-title .count{font-size:11px;color:var(--dim);font-weight:500;text-transform:none;letter-spacing:0}',
  '  .table-wrap{background:var(--surface);border-radius:14px;box-shadow:var(--shadow-sm);overflow-x:auto}',
  '  table{width:100%;border-collapse:collapse;font-size:13px;font-variant-numeric:tabular-nums}',
  '  thead th{background:var(--surface-2);color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:0.06em;font-weight:700;padding:13px 14px;text-align:right;border-bottom:1px solid var(--border);cursor:pointer;user-select:none;white-space:nowrap;transition:color 120ms}',
  '  thead th:first-child{text-align:left}',
  '  thead th:hover{color:var(--text)}',
  '  thead th.sorted{color:var(--blue)}',
  '  tbody td{padding:12px 14px;text-align:right;border-bottom:1px solid var(--border);color:var(--text);white-space:nowrap;font-weight:600}',
  '  tbody td:first-child{text-align:left;color:var(--text);font-weight:700}',
  '  tbody tr:last-child td{border-bottom:none}',
  '  tbody tr:hover td{background:var(--surface-2)}',
  '  .empty,.loading{padding:48px 20px;text-align:center;color:var(--muted);font-size:13px}',
  '  .spinner{width:28px;height:28px;border:3px solid var(--border);border-top-color:var(--blue);border-radius:50%;animation:spin 0.8s linear infinite;margin:0 auto 12px}',
  '  @keyframes spin{to{transform:rotate(360deg)}}',
  '  .bars-wrap{background:var(--surface);padding:20px;border-radius:14px;box-shadow:var(--shadow-sm)}',
  '  .bars{display:flex;flex-direction:column;gap:10px}',
  '  .bar-row{display:grid;grid-template-columns:200px 1fr 100px;gap:12px;align-items:center;font-size:12px}',
  '  .bar-row .name{color:var(--text);font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
  '  .bar-row .track{background:var(--surface-3);height:16px;border-radius:4px;overflow:hidden;display:flex}',
  '  .bar-row .seg-input{background:linear-gradient(90deg,var(--blue),var(--indigo))}',
  '  .bar-row .seg-output{background:linear-gradient(90deg,var(--green),#059669)}',
  '  .bar-row .value{color:var(--text);text-align:right;font-variant-numeric:tabular-nums;font-weight:700}',
  '  .legend{display:flex;gap:16px;font-size:11px;color:var(--muted);margin-bottom:14px;flex-wrap:wrap;font-weight:700;text-transform:uppercase;letter-spacing:0.04em}',
  '  .legend .sw{display:inline-block;width:12px;height:12px;border-radius:3px;margin-right:6px;vertical-align:middle}',
  '  .pies{display:grid;grid-template-columns:repeat(auto-fit,minmax(340px,1fr));gap:14px;margin-bottom:24px}',
  '  .pie-box{background:var(--surface);border-radius:14px;padding:20px;box-shadow:var(--shadow-sm)}',
  '  .pie-box h3{font-size:11px;color:var(--muted);font-weight:700;text-transform:uppercase;letter-spacing:0.06em;margin-bottom:14px}',
  '  .pie-body{display:flex;gap:18px;align-items:center;flex-wrap:wrap}',
  '  .pie-svg{flex-shrink:0}',
  '  .pie-legend{flex:1;min-width:150px;display:flex;flex-direction:column;gap:7px;font-size:12px}',
  '  .pie-legend .row{display:grid;grid-template-columns:12px 1fr auto;gap:8px;align-items:center;color:var(--muted)}',
  '  .pie-legend .row .sw{width:12px;height:12px;border-radius:3px}',
  '  .pie-legend .row .name{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--text);font-weight:600}',
  '  .pie-legend .row .pct{font-variant-numeric:tabular-nums;color:var(--muted);font-weight:500}',
  '  .pie-slice{transition:opacity 150ms}',
  '  .pie-slice:hover{opacity:0.78;cursor:pointer}',
  '  .meta{font-size:11px;color:var(--dim);margin-top:24px;padding-top:16px;border-top:1px solid var(--border);text-align:center;font-weight:500}',
  '</style>',
  '</head>',
  '<body>',
  '<div class="wrap">',
  '  <div class="header">',
  '    <h1><span class="dot"></span>OpenProxyRouter</h1>',
  '    <div class="controls" id="rangePicker">',
  '      <button data-preset="1h">1h</button>',
  '      <button data-preset="6h">6h</button>',
  '      <button data-preset="24h" class="active">24h</button>',
  '      <button data-preset="7d">7d</button>',
  '      <button data-preset="30d">30d</button>',
  '      <button data-preset="all">All</button>',
  '      <button id="refreshBtn" title="Refresh now">Refresh</button>',
  '    </div>',
  '  </div>',
  '  <div id="banner" class="banner"></div>',
  '  <div id="loading" class="loading"><div class="spinner"></div>Loading data...</div>',
  '  <div id="content" style="display:none">',
  '    <div class="cards" id="cards"></div>',
  '    <div class="section" id="piesSection" style="display:none">',
  '      <div class="section-title">Share by model</div>',
  '      <div class="pies">',
  '        <div class="pie-box"><h3>Requests share</h3><div class="pie-body" id="pieRequests"></div></div>',
  '        <div class="pie-box"><h3>Total tokens share</h3><div class="pie-body" id="pieTokens"></div></div>',
  '      </div>',
  '    </div>',
  '    <div class="section" id="barsSection" style="display:none">',
  '      <div class="section-title">Tokens by model</div>',
  '      <div class="bars-wrap">',
  '        <div class="legend">',
  '          <span><span class="sw" style="background:linear-gradient(90deg,#3b82f6,#6366f1)"></span>Input (incl. cache)</span>',
  '          <span><span class="sw" style="background:linear-gradient(90deg,#10b981,#059669)"></span>Output</span>',
  '        </div>',
  '        <div class="bars" id="bars"></div>',
  '      </div>',
  '    </div>',
  '    <div class="section">',
  '      <div class="section-title">Per-model breakdown <span class="count" id="rowCount"></span></div>',
  '      <div class="table-wrap">',
  '        <table id="detailTable">',
  '          <thead><tr>',
  '            <th data-col="model">Model</th>',
  '            <th data-col="requests" class="sorted">Requests</th>',
  '            <th data-col="input_tokens">Input</th>',
  '            <th data-col="output_tokens">Output</th>',
  '            <th data-col="cache_read">Cache Read</th>',
  '            <th data-col="total_tokens">Total</th>',
  '            <th data-col="avg_input_tokens">Avg In</th>',
  '            <th data-col="avg_output_tokens">Avg Out</th>',
  '          </tr></thead>',
  '          <tbody id="tableBody"></tbody>',
  '        </table>',
  '      </div>',
  '    </div>',
  '    <div class="meta" id="meta"></div>',
  '  </div>',
  '</div>',
  '<script>',
  '(function(){',
  '  "use strict";',
  '  var API = "/dashboard/api";',
  '  var PRESET_MS = {"1h":3600000,"6h":21600000,"24h":86400000,"7d":604800000,"30d":2592000000};',
  '  var STORAGE_KEY = "openproxyrouter.dashboard.preset";',
  '  function loadPresetFromStorage(){',
  '    try {',
  '      var saved = localStorage.getItem(STORAGE_KEY);',
  '      if(saved && (PRESET_MS[saved] || saved === "all")) return saved;',
  '    } catch(_e) {}',
  '    return "24h";',
  '  }',
  '  var state = { preset: loadPresetFromStorage(), sortCol: "requests", sortAsc: false, data: null };',
  '',
  '  function qs(id){ return document.getElementById(id); }',
  '  function fmt(n){',
  '    if(n==null||isNaN(n)) return "0";',
  '    var x = Number(n);',
  '    var abs = Math.abs(x);',
  '    if(abs >= 1e12) return trimZero(x/1e12) + "\u4e07\u4ebf";',
  '    if(abs >= 1e8)  return trimZero(x/1e8)  + "\u4ebf";',
  '    if(abs >= 1e4)  return trimZero(x/1e4)  + "\u4e07";',
  '    if(abs >= 1e3)  return trimZero(x/1e3)  + "\u5343";',
  '    if(Number.isInteger(x)) return String(x);',
  '    return trimZero(x);',
  '  }',
  '  function trimZero(x){',
  '    var s = x.toFixed(2);',
  '    return s.replace(/\\.?0+$/, "");',
  '  }',
  '  function fm1(n){ return (n==null||isNaN(n))?"0.0":Number(n).toFixed(1); }',
  '  var PALETTE = ["#3b82f6","#10b981","#f59e0b","#ec4899","#8b5cf6","#06b6d4","#f97316","#ef4444","#6366f1","#14b8a6","#d946ef","#facc15"];',
  '  function colorFor(i){ return PALETTE[i % PALETTE.length]; }',
  '',
  '  function showBanner(kind, msg){',
  '    var b = qs("banner");',
  '    b.className = "banner show " + kind;',
  '    b.textContent = msg;',
  '  }',
  '  function hideBanner(){ qs("banner").className = "banner"; }',
  '',
  '  function getRange(){',
  '    var now = Date.now();',
  '    if(state.preset === "all") return { from: 0, to: now };',
  '    var ms = PRESET_MS[state.preset] || 86400000;',
  '    return { from: now - ms, to: now };',
  '  }',
  '',
  '  function load(){',
  '    qs("loading").style.display = "block";',
  '    qs("content").style.display = "none";',
  '    hideBanner();',
  '    var r = getRange();',
  '    var url = API + "?from=" + r.from + "&to=" + r.to;',
  '    fetch(url).then(function(resp){',
  '      if(!resp.ok) throw new Error("HTTP " + resp.status);',
  '      return resp.json();',
  '    }).then(function(data){',
  '      state.data = data;',
  '      render(data);',
  '    }).catch(function(err){',
  '      qs("loading").style.display = "none";',
  '      showBanner("err", "Failed to load: " + (err && err.message ? err.message : err));',
  '    });',
  '  }',
  '',
  '  function render(data){',
  '    qs("loading").style.display = "none";',
  '    qs("content").style.display = "block";',
  '    if(data && data._store_unavailable){',
  '      showBanner("warn", "Store unavailable - token data is not persisted. Install better-sqlite3 to enable storage.");',
  '    }',
  '    var totals = (data && data.totals) || {};',
  '    var models = (data && data.models) || [];',
  '    renderCards(totals);',
  '    renderPies(models);',
  '    renderBars(models);',
  '    renderTable(models);',
  '    renderMeta(totals, models);',
  '  }',
  '',
  '  function renderCards(t){',
  '    var html = "";',
  '    html += card("Requests", fmt(t.requests), "", "blue");',
  '    html += card("Input tokens", fmt(t.input_tokens), "", "green");',
  '    html += card("Cache tokens", fmt(t.cache_read), "", "amber");',
  '    html += card("Output tokens", fmt(t.output_tokens), "", "pink");',
  '    html += card("Total tokens", fmt(t.total_tokens), "", "purple");',
  '    qs("cards").innerHTML = html;',
  '  }',
  '  function card(label, value, sub, tone){',
  '    var cls = tone ? "card tone-" + tone : "card";',
  '    var s = sub ? \'<div class="sub">\' + escapeHtml(sub) + \'</div>\' : "";',
  '    return \'<div class="\' + cls + \'"><div class="label">\' + escapeHtml(label) + \'</div><div class="value">\' + escapeHtml(value) + \'</div>\' + s + \'</div>\';',
  '  }',
  '  function escapeHtml(s){',
  '    if(s==null) return "";',
  '    return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");',
  '  }',
  '',
  '  function renderPies(models){',
  '    if(!models || models.length === 0){ qs("piesSection").style.display = "none"; return; }',
  '    var reqSeries = models.map(function(r){ return { name: r.model, value: r.requests || 0 }; })',
  '      .filter(function(x){ return x.value > 0; })',
  '      .sort(function(a,b){ return b.value - a.value; });',
  '    var tokSeries = models.map(function(r){ return { name: r.model, value: (r.input_tokens||0) + (r.output_tokens||0) + (r.cache_read||0) }; })',
  '      .filter(function(x){ return x.value > 0; })',
  '      .sort(function(a,b){ return b.value - a.value; });',
  '    if(reqSeries.length === 0 && tokSeries.length === 0){ qs("piesSection").style.display = "none"; return; }',
  '    qs("piesSection").style.display = "block";',
  '    qs("pieRequests").innerHTML = renderPie(reqSeries, false);',
  '    qs("pieTokens").innerHTML = renderPie(tokSeries, true);',
  '  }',
  '',
  '  function renderPie(series, isTokens){',
  '    if(!series || series.length === 0){',
  '      return \'<div style="color:var(--dim);font-size:12px;padding:20px">No data</div>\';',
  '    }',
  '    var total = 0;',
  '    for(var i=0;i<series.length;i++) total += series[i].value;',
  '    if(total <= 0){',
  '      return \'<div style="color:var(--dim);font-size:12px;padding:20px">No data</div>\';',
  '    }',
  '    var size = 140, cx = size/2, cy = size/2, r = size/2 - 2;',
  '    var svg = \'<svg class="pie-svg" width="\' + size + \'" height="\' + size + \'" viewBox="0 0 \' + size + \' \' + size + \'">\';',
  '    if(series.length === 1){',
  '      svg += \'<circle cx="\' + cx + \'" cy="\' + cy + \'" r="\' + r + \'" fill="\' + colorFor(0) + \'" class="pie-slice"><title>\' + escapeHtml(series[0].name) + \': 100%</title></circle>\';',
  '    } else {',
  '      var startAngle = -Math.PI/2;',
  '      for(var j=0;j<series.length;j++){',
  '        var frac = series[j].value / total;',
  '        var endAngle = startAngle + frac * Math.PI * 2;',
  '        var largeArc = frac > 0.5 ? 1 : 0;',
  '        var x1 = cx + r * Math.cos(startAngle);',
  '        var y1 = cy + r * Math.sin(startAngle);',
  '        var x2 = cx + r * Math.cos(endAngle);',
  '        var y2 = cy + r * Math.sin(endAngle);',
  '        var d = "M " + cx + " " + cy + " L " + x1.toFixed(3) + " " + y1.toFixed(3) + " A " + r + " " + r + " 0 " + largeArc + " 1 " + x2.toFixed(3) + " " + y2.toFixed(3) + " Z";',
  '        var pct = (frac * 100).toFixed(1);',
  '        svg += \'<path class="pie-slice" d="\' + d + \'" fill="\' + colorFor(j) + \'"><title>\' + escapeHtml(series[j].name) + ": " + pct + "% (" + fmt(series[j].value) + ")" + \'</title></path>\';',
  '        startAngle = endAngle;',
  '      }',
  '    }',
  '    svg += \'<circle cx="\' + cx + \'" cy="\' + cy + \'" r="\' + (r * 0.55) + \'" fill="var(--surface)"/>\';',
  '    svg += \'<text x="\' + cx + \'" y="\' + (cy - 4) + \'" text-anchor="middle" fill="var(--muted)" font-size="10" font-family="sans-serif">Total</text>\';',
  '    svg += \'<text x="\' + cx + \'" y="\' + (cy + 12) + \'" text-anchor="middle" fill="var(--text)" font-size="14" font-weight="600" font-family="sans-serif">\' + fmt(total) + \'</text>\';',
  '    svg += \'</svg>\';',
  '    var legend = \'<div class="pie-legend">\';',
  '    var max = Math.min(series.length, 8);',
  '    for(var k=0;k<max;k++){',
  '      var p = (series[k].value / total * 100).toFixed(1);',
  '      legend += \'<div class="row">\';',
  '      legend += \'<span class="sw" style="background:\' + colorFor(k) + \'"></span>\';',
  '      legend += \'<span class="name" title="\' + escapeHtml(series[k].name) + \'">\' + escapeHtml(series[k].name) + \'</span>\';',
  '      legend += \'<span class="pct">\' + p + \'% &middot; \' + fmt(series[k].value) + \'</span>\';',
  '      legend += \'</div>\';',
  '    }',
  '    if(series.length > max){',
  '      var restVal = 0;',
  '      for(var m=max;m<series.length;m++) restVal += series[m].value;',
  '      var restPct = (restVal / total * 100).toFixed(1);',
  '      legend += \'<div class="row"><span class="sw" style="background:var(--dim)"></span><span class="name">+\' + (series.length - max) + \' more</span><span class="pct">\' + restPct + \'% &middot; \' + fmt(restVal) + \'</span></div>\';',
  '    }',
  '    legend += \'</div>\';',
  '    return svg + legend;',
  '  }',
  '',
  '  function renderBars(models){',
  '    if(!models || models.length === 0){ qs("barsSection").style.display = "none"; return; }',
  '    qs("barsSection").style.display = "block";',
  '    var top = models.slice().sort(function(a,b){',
  '      var ta = (a.input_tokens||0) + (a.output_tokens||0) + (a.cache_read||0);',
  '      var tb = (b.input_tokens||0) + (b.output_tokens||0) + (b.cache_read||0);',
  '      return tb - ta;',
  '    }).slice(0, 10);',
  '    var max = 0;',
  '    for(var i=0;i<top.length;i++){',
  '      var t = (top[i].input_tokens||0) + (top[i].output_tokens||0) + (top[i].cache_read||0);',
  '      if(t > max) max = t;',
  '    }',
  '    if(max === 0) max = 1;',
  '    var html = "";',
  '    for(var j=0;j<top.length;j++){',
  '      var r = top[j];',
  '      var inp = (r.input_tokens||0) + (r.cache_read||0);',
  '      var out = r.output_tokens || 0;',
  '      var total = inp + out;',
  '      var inpPct = (inp / max * 100).toFixed(1);',
  '      var outPct = (out / max * 100).toFixed(1);',
  '      html += \'<div class="bar-row">\';',
  '      html += \'<div class="name" title="\' + escapeHtml(r.model) + \'">\' + escapeHtml(r.model) + \'</div>\';',
  '      html += \'<div class="track">\';',
  '      html += \'<div class="seg-input" style="width:\' + inpPct + \'%"></div>\';',
  '      html += \'<div class="seg-output" style="width:\' + outPct + \'%"></div>\';',
  '      html += \'</div>\';',
  '      html += \'<div class="value">\' + fmt(total) + \'</div>\';',
  '      html += \'</div>\';',
  '    }',
  '    qs("bars").innerHTML = html;',
  '  }',
  '',
  '  function sortRows(rows){',
  '    var col = state.sortCol, asc = state.sortAsc;',
  '    var copy = rows.slice();',
  '    copy.sort(function(a,b){',
  '      var va = a[col], vb = b[col];',
  '      if(va == null) va = 0; if(vb == null) vb = 0;',
  '      if(typeof va === "string"){',
  '        return asc ? String(va).localeCompare(String(vb)) : String(vb).localeCompare(String(va));',
  '      }',
  '      return asc ? (va - vb) : (vb - va);',
  '    });',
  '    return copy;',
  '  }',
  '',
  '  function renderTable(models){',
  '    var rows = sortRows(models);',
  '    qs("rowCount").textContent = rows.length + " rows";',
  '    if(rows.length === 0){',
  '      qs("tableBody").innerHTML = \'<tr><td colspan="8" class="empty">No data in the selected time range</td></tr>\';',
  '      return;',
  '    }',
  '    var html = "";',
  '    for(var i=0;i<rows.length;i++){',
  '      var r = rows[i];',
  '      var total = (r.input_tokens||0) + (r.output_tokens||0);',
  '      html += "<tr>";',
  '      html += "<td>" + escapeHtml(r.model || "-") + "</td>";',
  '      html += "<td>" + fmt(r.requests) + "</td>";',
  '      html += "<td>" + fmt(r.input_tokens) + "</td>";',
  '      html += "<td>" + fmt(r.output_tokens) + "</td>";',
  '      html += "<td>" + fmt(r.cache_read) + "</td>";',
  '      html += "<td>" + fmt(total) + "</td>";',
  '      html += "<td>" + fm1(r.avg_input_tokens) + "</td>";',
  '      html += "<td>" + fm1(r.avg_output_tokens) + "</td>";',
  '      html += "</tr>";',
  '    }',
  '    qs("tableBody").innerHTML = html;',
  '    var ths = document.querySelectorAll("thead th");',
  '    for(var j=0;j<ths.length;j++){',
  '      var th = ths[j];',
  '      if(th.dataset.col === state.sortCol) th.classList.add("sorted");',
  '      else th.classList.remove("sorted");',
  '    }',
  '  }',
  '',
  '  function renderMeta(totals, models){',
  '    var parts = [];',
  '    parts.push(models.length + " models");',
  '    if(totals.first_ts){ parts.push("first: " + new Date(totals.first_ts).toLocaleString()); }',
  '    if(totals.last_ts){ parts.push("last: " + new Date(totals.last_ts).toLocaleString()); }',
  '    parts.push("updated: " + new Date().toLocaleTimeString());',
  '    qs("meta").textContent = parts.join(" | ");',
  '  }',
  '',
  '  function setupEvents(){',
  '    var btns = document.querySelectorAll("#rangePicker button[data-preset]");',
  '    for(var i=0;i<btns.length;i++){',
  '      (function(btn){',
  '        btn.addEventListener("click", function(){',
  '          for(var j=0;j<btns.length;j++) btns[j].classList.remove("active");',
  '          btn.classList.add("active");',
  '          state.preset = btn.dataset.preset;',
  '          try { localStorage.setItem(STORAGE_KEY, state.preset); } catch(_e) {}',
  '          load();',
  '        });',
  '      })(btns[i]);',
  '    }',
  '    qs("refreshBtn").addEventListener("click", load);',
  '    var ths = document.querySelectorAll("thead th");',
  '    for(var k=0;k<ths.length;k++){',
  '      (function(th){',
  '        th.addEventListener("click", function(){',
  '          var col = th.dataset.col;',
  '          if(!col) return;',
  '          if(state.sortCol === col){ state.sortAsc = !state.sortAsc; }',
  '          else { state.sortCol = col; state.sortAsc = false; }',
  '          if(state.data) renderTable(state.data.models || []);',
  '        });',
  '      })(ths[k]);',
  '    }',
  '  }',
  '',
  '  function init(){',
  '    var allBtns = document.querySelectorAll("#rangePicker button[data-preset]");',
  '    for(var i=0;i<allBtns.length;i++){',
  '      allBtns[i].classList.toggle("active", allBtns[i].dataset.preset === state.preset);',
  '    }',
  '    setupEvents();',
  '    load();',
  '  }',
  '',
  '  if(document.readyState === "loading") document.addEventListener("DOMContentLoaded", init);',
  '  else init();',
  '})();',
  '</script>',
  '</body>',
  '</html>'
].join('\n');

function dashboardHtml() {
  return HTML;
}

module.exports = { dashboardHtml };
